THIS_FILE := $(lastword $(MAKEFILE_LIST))
VALID_TOOLCHAINS := pnacl glibc clang-newlib mac

TOOLCHAIN = pnacl

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/nacl_sdk_root)

CONFIG = Release

include $(NACL_SDK_ROOT)/tools/common.mk

LIBS = avformat avcodec avfilter avutil x264 swresample ppapi_cpp ppapi pthread nacl_io

TARGET = golive

CFLAGS = -Wall
SOURCES = golive.cc

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

# The PNaCl workflow uses both an unstripped and finalized/stripped binary.
# On NaCl, only produce a stripped binary for Release configs (not Debug).
ifneq (,$(or $(findstring pnacl,$(TOOLCHAIN)),$(findstring Release,$(CONFIG))))
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))

.PHONY: package

package:
	zip -x '*.png' -9 golive.zip * pnacl/Release/golive.nmf pnacl/Release/golive.pexe
