VALID_TOOLCHAINS := pnacl glibc clang-newlib mac

TOOLCHAIN = pnacl

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/nacl_sdk_root)

CONFIG = Debug

include $(NACL_SDK_ROOT)/tools/common.mk

LIBS = ppapi_cpp ppapi pthread avformat avcodec avutil nacl_io # mp3lame vorbis theora vpx swscale swresample vorbisenc ogg

TARGET = golive

CFLAGS = -Wall
SOURCES = golive.cc

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

# The PNaCl workflow uses both an unstripped and finalized/stripped binary.
# On NaCl, only produce a stripped binary for Release configs (not Debug).
ifneq (,$(or $(findstring pnacl,$(TOOLCHAIN)),$(findstring Release,$(CONFIG))))
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
